### ISSUE TITLE
Pulled sub directories save to root

### ISSUE THREAD

**Issue by jeremydouglas** [thisbythem/stag#13]
When I pull the content down, and reference a sub directory, for instance: '_config/users', the users folder will end up in the root directory.

Pulling the users folder is handy to keep users that are added on the server.

**Comment by nobodyiscertain** [comment]
@jeremydouglas What strategy are you using in your server config?

**Comment by jeremydouglas** [comment]
I'm using rsync.

**Comment by nobodyiscertain** [comment]
Hi @jeremydouglas 

I was able to replicate the issue and deployed a bugfix for it. If you download and install v1.1.1 that should fix the issue.

**Comment by jeremydouglas** [comment]
Amazing and thank you!

**Comment by jeremydouglas** [comment]
@nobodyiscertain I've tested this and the update works for me. Thanks!

**Comment by mikemartin** [comment]
@nobodyiscertain Yeah! Thanks guys!

**Comment by nobodyiscertain** [comment]
:+1:
